var main=function()
{
  
$('.tab').on("click",function()
{
 var id=$(this).attr('id');
 if(id==="HAbout")
  {
  $('.tab').removeClass('current');
  $(this).addClass('current');
  $('.jumbotron').removeClass('hide');
  $('.jumbotron').removeClass('show');
  $("#JHome.jumbotron").addClass('hide');
  $("#JAbout.jumbotron").addClass('show');
  $("#JEducation.jumbotron").addClass('hide');
  $("#JEmploymentHistory.jumbotron").addClass('hide');
  $("#JEmploymentPeaceCoffee1.jumbotron").addClass('hide');
  $("#JEmploymentPeaceCoffee2.jumbotron").addClass('hide');
  $("#JEmploymentBarista.jumbotron").addClass('hide');
  $("#JEmploymentPeaceCoffee3.jumbotron").addClass('hide');
  }
    else if(id==="HHome")
    {
    $('.tab').removeClass('current');
    $(this).addClass('current');
    $('.jumbotron').removeClass('hide');
    $('.jumbotron').removeClass('show');
    $("#JHome.jumbotron").addClass('show');
    $("#JAbout.jumbotron").addClass('hide');
    $("#JEducation.jumbotron").addClass('hide');
    $("#JEmploymentHistory.jumbotron").addClass('hide');
    $("#JEmploymentPeaceCoffee1.jumbotron").addClass('hide');
    $("#JEmploymentPeaceCoffee2.jumbotron").addClass('hide');
    $("#JEmploymentBarista.jumbotron").addClass('hide');
    $("#JEmploymentPeaceCoffee3.jumbotron").addClass('hide');
    }
      else if(id==="HEducation")
      {
      $('.tab').removeClass('current');
      $(this).addClass('current');
      $('.jumbotron').removeClass('hide');
      $('.jumbotron').removeClass('show');
      $("#JHome.jumbotron").addClass('hide');
      $("#JAbout.jumbotron").addClass('hide');
      $("#JEducation.jumbotron").addClass('show');
      $("#JEmploymentHistory.jumbotron").addClass('hide');
      $("#JEmploymentPeaceCoffee1.jumbotron").addClass('hide');
      $("#JEmploymentPeaceCoffee2.jumbotron").addClass('hide');
      $("#JEmploymentBarista.jumbotron").addClass('hide');
      $("#JEmploymentPeaceCoffee3.jumbotron").addClass('hide');
      }
        else if(id==="HResume")
        {
        $('.tab').removeClass('current');
        $(this).addClass('current');
        $('.jumbotron').removeClass('hide');
        $('.jumbotron').removeClass('show');
        $("#JHome.jumbotron").addClass('hide');
        $("#JAbout.jumbotron").addClass('hide');
        $("#JEducation.jumbotron").addClass('hide');
        $("#JEmploymentHistory.jumbotron").addClass('show');
        $("#JEmploymentPeaceCoffee1.jumbotron").addClass('show');
        $("#JEmploymentPeaceCoffee2.jumbotron").addClass('show');
        $("#JEmploymentBarista.jumbotron").addClass('show');
        $("#JEmploymentPeaceCoffee3.jumbotron").addClass('show');
        }
}  
); 
};
$(document).ready(main);
